-- Creation tablespace

CREATE TABLESPACE SSB
DATAFILE 'C:\Tools\Oracle-HOME\oradata\ORCLE\orclpdb\SSB.DBF' SIZE 5M
AUTOEXTEND ON MAXSIZE UNLIMITED;

--Ajout datafile 
ALTER TABLESPACE SSB
ADD DATAFILE 'C:\Tools\Oracle-HOME\oradata\ORCLE\orclpdb\SSB1.DBF'
   SIZE 20M
   AUTOEXTEND ON MAXSIZE UNLIMITED;
--Creation de l'utilisateur

CREATE USER ssb
IDENTIFIED BY ssb
DEFAULT TABLESPACE SSB
QUOTA UNLIMITED ON SSB;

-- Attribution des privileges

GRANT CREATE SESSION,
CREATE TABLE,
CREATE ANY DIRECTORY,
UNLIMITED TABLESPACE 
TO ssb;

CREATE OR REPLACE DIRECTORY ssb_dir AS 'D:\dbgen';

GRANT READ, WRITE ON DIRECTORY ssb_dir TO ssb;
GRANT ALL PRIVILEGES TO ssb;
